[package]
name = "rofka"
version = "0.1.0"
authors = ["Rob Hurkes <rhurkes@gmail.com>"]
edition = "2018"

[dependencies]
rdkafka = { version = "0.24", features = ["cmake-build"] }
rocksdb = "0.15"
serde = "1.0"
serde_json = "1.0"
